modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/jellysquid3/phosphor-forge/issues"
license="LGPL 3.0"

[[mods]]
modId="phosphor"
version="1.16.3-0.1.0"
displayName="Phosphor"
displayURL="https://www.curseforge.com/minecraft/mc-mods/phosphor-forge"
logoFile="icon.png"
authors="JellySquid"
description='''
Phosphor is an optimization mod for Minecraft which improves the performance of the lighting engine, resulting in significantly reduced world generation times and improved server tick rates.

You can find the source code under the GNU LGPLv3 on GitHub: https://github.com/jellysquid3/phosphor-forge
'''
